apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: function
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: estromenko/function:1
          ports:
            - containerPort: 8080
