apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: knative-operator
  namespace: knative-operator
spec:
  releaseName: knative-operator
  chart:
    spec:
      chart: knative-operator
      version: "v1.20.0"
      sourceRef:
        kind: HelmRepository
        name: knative-operator
        namespace: knative-operator
  interval: 5m
  install:
    remediation:
      retries: 3
